PRAGMA synchronous = off;
PRAGMA journal_mode = MEMORY;
PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS studios;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS movie_genres;
DROP TABLE IF EXISTS movie_studios;
DROP TABLE IF EXISTS movie_companies;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS credits;
CREATE TABLE IF NOT EXISTS movies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL UNIQUE,
  upc TEXT DEFAULT NULL,
  title TEXT NOT NULL,
  original_title TEXT NOT NULL,
  sort_title TEXT NOT NULL,
  overview TEXT DEFAULT NULL,
  rating TEXT NOT NULL DEFAULT '',
  length INTEGER NOT NULL DEFAULT 0,
  year INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS genres (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS movie_genres (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  UNIQUE(movie_id, genre_id)
);
CREATE TABLE IF NOT EXISTS studios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS movie_studios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL,
  studio_id INTEGER NOT NULL,
  UNIQUE(movie_id, studio_id)
);
CREATE TABLE IF NOT EXISTS companies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS movie_companies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL,
  company_id INTEGER NOT NULL,
  UNIQUE(movie_id, company_id)
);
CREATE TABLE IF NOT EXISTS persons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL DEFAULT '',
  middle_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  birth_year INTEGER NOT NULL DEFAULT 0,
  UNIQUE(first_name, middle_name, last_name, birth_year)
);
CREATE TABLE IF NOT EXISTS roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  role TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS credits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  credit_type TEXT NOT NULL DEFAULT '',
  credit_subtype TEXT NOT NULL DEFAULT ''
);